// src/views/home/index.vue
<template>
    <div class="homeContainer">
        home-page
        <div>{{ home.msg }}</div>
        <div>{{ auto }}</div>
        <div>使用二次封装axios请求数据</div>
        <ul>
            <li v-for="item in home.categoryList" :key="item.id">{{ item.name }}</li>
        </ul>
    </div>
</template>

<script setup lang="ts">
import useStore from '@/stores'
const { home } = useStore()

// 可以不用再引入 ref 等api，直接使用
const auto = ref('自动引入api')

// 使用pinia发请求(二次封装的axios)，以及管理数据
onMounted(() => {
    home.getAllCategory()
})
</script>

<style scoped lang="less">

</style>

// src/pages/home/index.tsx
import React, { useEffect } from 'react'

// 使用Mobx：
// 1.从 @/store 引入 useStore 统一管理函数
// 2.从 mobx-react-lite 引入 observer，并包裹当前组件，使mobx和react连接
import useStore from '../../store'
import { observer } from 'mobx-react-lite'

function Home() {
    const { home } = useStore()

    useEffect(() => {
        home.getAllCategory()
    }, [])

    return (
        <div>
            Home-page
            <div>{home.msg}</div>
            <div>使用二次封装axios请求数据</div>
            <ul>
                {
                    home.categoryList.length &&
                    home.categoryList.map(
                        item => <li key={item.id}>{item.name}</li>
                    )
                }
            </ul>
        </div>
    )
}

export default observer(Home)
