// src/pages/layout/index.tsx
import React, { Suspense } from 'react'
import style from './index.module.less'
import { Outlet } from 'react-router-dom'

import AppHeader from '../../components/app-header'
import AppNav from '../../components/app-nav'
import AppFooter from '../../components/app-footer'
import AppLoading from '../../components/app-loading'


function Layout() {
    return (
        <div className={style.layoutContainer}>
            <AppNav></AppNav>
            <AppHeader></AppHeader>
            <main className="mainContainer">
                <Suspense
                    fallback={<AppLoading />}
                >
                    <Outlet></Outlet>
                </Suspense>
            </main>
            <AppFooter></AppFooter>
        </div>
    )
}

export default Layout

// src/views/Layout.vue
<template>
    <div class="layoutContainer">
        <AppNav></AppNav>
        <AppHeader></AppHeader>
        <main class="mainContainer">
            <router-view></router-view>
        </main>
        <AppFooter></AppFooter>
    </div>
</template>

<script>
import AppNav from '@/components/app-nav/index.vue'
import AppHeader from '@/components/app-header/index.vue'
import AppFooter from '@/components/app-footer/index.vue'
export default {
    name: 'Layout',
    components: { AppNav, AppHeader, AppFooter }
}
</script>

<style lang="less" scoped>
.mainContainer {
    padding: 20px;
}
</style>
