// src/components/app-nav/index.tsx
import style from './index.module.less'
import { Link } from 'react-router-dom'
import React from 'react'

function AppNav() {
    return (
        <div className={style.appNav}>
            AppNav
            <div className="link">
                <Link to='/'>Home</Link>&nbsp;&nbsp;
                <Link to='/about'>About</Link>
            </div>
        </div>
    )
}

export default AppNav

// src/components/app-nav/index.vue
<template>
    <nav class="app-nav">
        app-nav
        <div class="routerLink">
            <routerLink to="/">Home</routerLink>&nbsp;&nbsp;
            <routerLink to="/about">About</routerLink>
        </div>
    </nav>
</template>

<script>
export default {
    name: 'AppNav'
}
</script>

<style lang="less" scoped>
.app-nav {
    background-color: cadetblue;

    .routerLink {
        padding: 10px;
    }
}
</style>
